from dotenv import find_dotenv
from starlette.config import Config

config = Config(find_dotenv())
DEBUG = config("DEBUG", cast=bool, default=False)
DATABASE_HOST = config("DATABASE_HOST", default=None)
DATABASE_USER = config("DATABASE_USER", default=None)
DATABASE_NAME = config("DATABASE_NAME", default=None)
DATABASE_PASSWORD = config("DATABASE_PASSWORD", default=None)
DATABASE_PORT = config("DATABASE_PORT", cast=int, default=5432)
DATABASE_URL = config("DATABASE_URL", default=None)
BUGSNAG_API_KEY = config("BUGSNAG_API_KEY", default=None)
RELEASE_STAGE = config("RELEASE_STAGE", default="")
LOG_APP_ID = config("LOG_APP_ID", default="")
REDIS_HOST = config("REDIS_HOST", default=None)
CMS_APP_ID = config("GDS_SELF_APP_ID", default="")
API_URL = config("GDS_API_URL", default="")
API_KEY = config("GDS_API_KEY", default="")
STORELOCAL_OWNER_ID = config("STORELOCAL_OWNER_ID", default="")
COMMON_DATA_APP_ID = config("COMMON_DATA_APP_ID", default="")
STORAGEFRONT_OWNER_ID = config("STORAGEFRONT_OWNER_ID", default="")
GDS_SELF_APP_ID = config("GDS_SELF_APP_ID", default="")
KIOSK_WEBSITE_URL = config("KIOSK_WEBSITE_URL", default="")
FILE_APP_ID = config("FILE_APP_ID", default="")
DIGITAL_SIGNAGE_DOMAIN = config("DIGITAL_SIGNAGE_DOMAIN", default="")
CMS_BUNDLE_DOMAIN = config("CMS_BUNDLE_DOMAIN", default="")

GOOGLE_PLACE_SEARCH_URL = config("GOOGLE_PLACE_SEARCH_URL", default="")
GOOGLE_PLACE_DETAILS_URL = config("GOOGLE_PLACE_DETAILS_URL", default="")
GOOGLE_API_KEY = config("GOOGLE_API_KEY", default="")
GOOGLE_API_CALL_LIMIT = config("GOOGLE_API_CALL_LIMIT", default="")
YELP_API_KEY = config("YELP_API_KEY", default="")
YELP_API_CALL_LIMIT = config("YELP_API_CALL_LIMIT", default="")
