#FROM node:alpine
#WORKDIR "/home/app/hummingbird/"
#COPY ./package.json ./
#RUN npm install
#COPY . .
#CMD ["npm", "run", "dev"]

#FROM node:9-alpine
FROM node:10.15.0

WORKDIR "/home/app/hummingbird/"
COPY ./package.json ./
#RUN npm install -g @vue/cli-service-global
RUN npm install

# --no-cache: download package index on-the-fly, no need to cleanup afterwards
# --virtual: bundle packages, remove whole bundle at once, when done
#RUN apk --no-cache --virtual build-dependencies add \
#    @vue/cli \
#    python \
#    make \
#    g++ \
#    && npm install \
#    && apk del build-dependencies


COPY . .
CMD ["npm", "run", "serve"]
